### ISSUE TITLE
Quelques petites erreurs :D

### ISSUE THREAD

**Issue by Valbou** [salocinski/MyPass#2]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.jtattoo.plaf.BasePanelUI (file:/C:/Users/Valbou/Desktop/MyPass-master/Mypass/dist/lib/JTattoo-1.6.11.jar) to field javax.swing.ClientPropertyKey.PopupFactory_FORCE_HEAVYWEIGHT_POPUP
WARNING: Please consider reporting this to the maintainers of com.jtattoo.plaf.BasePanelUI
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Chargement du driver...
Driver OK...
Connexion a la BDD...
Problème d'informations liées à la BDD
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at DAO.PersonneDAO.chargerListePersonne(PersonneDAO.java:106)
        at IHM.Accueil.initComboBox(Accueil.java:43)
        at IHM.Accueil.<init>(Accueil.java:28)
        at IHM.Accueil$5.run(Accueil.java:248)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.desktop/java.awt.EventQueue.access$500(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.desktop/java.awt.EventQueue$3.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by salocinski** [comment]
Problème rencontre lorsque l'application est lancée sans injection du script SQL.
